replicaCount: 1

image:
  repository: yeasy/simple-web
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: ecrews.dev
      paths:
        - /weather(/|$)(.*)
  tls:
    - secretName: ecrews-tls
      hosts:
        - ecrews.dev

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
