replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ericcrews/weather
  tag: 5b09d38d3bf04b5d17f1319384c3eee778f84b5b

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ecrews.dev
      paths:
        - /weather
  tls:
    - secretName: ecrews-tls
      hosts:
        - ecrews.dev

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
